sonar.organization=loliman
sonar.projectKey=loliman_shortbox-next
sonar.projectName=shortbox-next

sonar.sources=app,src
sonar.tests=app,src

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=.next/**,dist/**,node_modules/**,coverage/**,public/**,next-env.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
